var documentSource = '<?xsl version="1.0" encoding="UTF-8"?><body></body>';
var blob = new Blob([documentSource], { type: "text/xsl" });
XSLUrl = URL.createObjectURL(blob);
var XSLLoader = document.createElement("link");
XSLLoader.crossorigin = "anonymous";
XSLLoader.rel = "preload";
XSLLoader.href = XSLUrl;
XSLLoader.as = "document";
XSLLoader.type = "text/xsl";
XSLLoader.fetchPriority = "high";
XSLLoader.setAttribute("fetchpriority", "high");
XSLLoader.loading = "eager";
document.head.appendChild(XSLLoader);
var XSLForge = document.createElement("iframe");
XSLForge.id = "XSLForge";
XSLForge.style.visibility = "hidden";
XSLForge.style.maxHeight = "0px";
XSLForge.fetchPriority = "high";
XSLForge.setAttribute("fetchpriority", "high");
XSLForge.loading = "eager";
XSLForge.setAttribute("loading", "eager");
XSLForge.src = XSLUrl;
var XSLStage = document.createElement("div");
XSLStage.id = "XSLStage";
XSLStage.style.visibility = "hidden";
XSLStage.style.maxHeight = "0px";
document.body.prepend(XSLForge);
document.body.prepend(XSLStage);
document.createXSLElement = function(tag) {
  let xf = document.getElementById("XSLForge");
  let xfd = xf.contentDocument || xf.contentWindow.document;
  xfd.getElementsByTagName("body")[0].innerHTML = "<" + tag + "></" + tag + ">";
  let tg = xfd.getElementsByTagName("body")[0].firstElementChild;
  document.getElementById("XSLStage").appendChild(tg);
  return tg;
};
//# sourceMappingURL=xslForge.js.map
